# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 06:15
from __future__ import unicode_literals

import api.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EducationInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.TextField()),
                ('degree', models.TextField()),
                ('agreegate', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Intrest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intrest', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('dob', models.DateField()),
                ('height_field', models.IntegerField(blank=True, default=0, null=True)),
                ('width_field', models.IntegerField(blank=True, default=0, null=True)),
                ('profilePic', models.ImageField(blank=True, height_field='height_field', null=True, upload_to=api.models.upload_location, width_field='width_field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='WorkExperience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_intern', models.TextField(blank=True, null=True)),
                ('to_intern', models.TextField(blank=True, null=True)),
                ('company_intern', models.TextField(blank=True, null=True)),
                ('title_intern', models.TextField(blank=True, null=True)),
                ('status_intern', models.TextField(blank=True, null=True)),
                ('from_job', models.TextField(blank=True, null=True)),
                ('to_job', models.TextField(blank=True, null=True)),
                ('company_job', models.TextField(blank=True, null=True)),
                ('title_job', models.TextField(blank=True, null=True)),
                ('from_freelancer', models.TextField(blank=True, null=True)),
                ('to_freelancer', models.TextField(blank=True, null=True)),
                ('client_freelancer', models.TextField(blank=True, null=True)),
                ('project_freelancer', models.TextField(blank=True, null=True)),
                ('status_freelancer', models.TextField(blank=True, null=True)),
                ('from_self', models.TextField(blank=True, null=True)),
                ('to_self', models.TextField(blank=True, null=True)),
                ('project_self', models.TextField(blank=True, null=True)),
                ('status_self', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
