# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 11:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0005_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_book', models.TextField(blank=True, null=True)),
                ('publisher_book', models.TextField(blank=True, null=True)),
                ('detail_book', models.TextField(blank=True, null=True)),
                ('isbn_book', models.TextField(blank=True, null=True)),
                ('year_poster', models.TextField(blank=True, null=True)),
                ('org_poster', models.TextField(blank=True, null=True)),
                ('detail_poster', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
