# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-04 12:06
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0007_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_a', models.TextField(blank=True, null=True)),
                ('org_a', models.TextField(blank=True, null=True)),
                ('detail_a', models.TextField(blank=True, null=True)),
                ('year_s', models.TextField(blank=True, null=True)),
                ('org_s', models.TextField(blank=True, null=True)),
                ('detail_s', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
